travis:
  secure:
    BINSTAR_TOKEN: mvq0APFSOIn9ZnxpgbbbPBGOYds5gA0jQ8GGN07kkaM9y89HwVOn7kaIzoczJQ2Mn22JPsByXMd4dDnLTf8emCo1TJfqz5QmNem0wcxBrcyRkojJtwVHbxooGzPMskaPrkSxmgsvqKiaToS1AsBI19RRffnPve/t6TImDf+IXqIzx4W6dQqe+zNbYJMaDlLVMqikcPD/J5c6RfuJy1y4Cb2lAv7BfQaZKqxhUGlAUC7skP00umDKQKx5ZqTiiqs0OVbgQOmRktq17BC3kaHG4eu0hANpUtA7m9NTbWfze1ZoTM1JMEjHLhUoX/KlYxp0cHdDJpkEuylGfoAdHF0zAtvuKQs9OD9Ep6iTpmx0jktR48m380/hZZ+7dpBzbnWO0JkRq0O2RqIK9y6tImfXPqIqo5LnlsnzcA2f2XSu0jowar907/Jz0leTAl/hhhelBseGCAPi/ier0Dks9lQinBJk40SjBHJV56qBmP+2XHpOnfDceIzgxbSS+lpSTnApYBqLY/75BNm+Yd+1PFQCaZyeHgRLx2KC/cEvMIc3WoetbxUjZL/8q4cWrUwmQEPDjbVOzroXNEcNEhtkcSLjqMqx1B8uUU9/3J7Romx6xPlNqkfWxYq8OortfvesWUgWhiyujfjwHkJsSTh30Fy/ql4MIC0GnbSxraHCK1UG9m4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
