travis:
  secure:
    BINSTAR_TOKEN: zHBadgfImPon0F1aKvEKRZCt4Ul9/M05ItqpsAlzBUFSNh9eCGbkvV1JTUdesQu7kChpf9j2G3u7+EChTLGnwAuRdEpHuIeE7k387Prj+VoFeCqY6o+xdRx60mOnCuoKEbAUbI9138qWlKD35ZCRUjn/foJyoeWcEF61oZIzR7vxy6AjJl3sWUSfFdz79KB9noRdakdsehXT1+u5Yko2G4XNCiIc6MTbzuAtqV8AoVqHVHnHjtccIqc1SI86gZ8kp8As8qfcwN1gA/NQ8hBmUM5kW72TUJ/yXFQadrzZFoqFjnO0lOWGXBx5X3Q6DPwV1mkpqaeGmGAdHzmFt2ZOJFEGTLeR9vCuPtlBGfFTVEDmxaRsVU2rCU8hfaNewSOp223Uo+tdkEXWI3h/UEJrnpFj9dYfm2zaVtOYjgoV9OyprsjXH8STH5ROpqqjh0Tk1W9mZJxKlCkk1Sv167TUsdHDfxWQ7RRMCR1Y0/A455KJYprNJypwTStJhw8OvTWBw/GgAWPILZVvCkGjLq4e20C/L+yowLsrW7VdxFfHtckdamr5g9ERo17i36nBM75g/q6Tf5DGOQcQcad/DLXtyM+OrOLe6afeHKcbGq36vnaQfsufHINykxEvvNbN0oYYC33c/vcNlLEZxZH6U/Pj5m8h6JG13OGXie0hfDMV21E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
